### ISSUE TITLE
Feature: Add versioned documentation

### ISSUE THREAD

**Issue by yardasol** [arfc/saltproc#102]
## Background and motivation
While working on SaltProc, I've run into several conundrums regarding the documentation
- Github Pages only seems to allow a single active deployment at a time
- Documentation in progress may not need to be pushed to the documentation website, especially if a feature is in development

There are several useful features that the documentation website should have:

- Documentation for previous versions of the software
- Stable (current) and development (bleeding edge) versions of the docs

Over the next several months, I will be doing heavy development of the codebase, and these features should be already set up.

## Description of idea
The above described features are available on readthedocs.
I propose we host the SaltProc documentation on readthedocs in order to take advantage of these features.

## Implementation details
We will need to get this all set-up before we can migrate. Luckily, there seems to be a good guide [here](https://docs.readthedocs.io/en/stable/tutorial/)

## Potential snags
This could take a few tries to get right. We also will need to change our `deploy-docs` workflow accordingly (or potentially remove it entirely)

**Comment by yardasol** [comment]
Before jumping ship towards read-the-docs, try doing this first natively with github pages.
- https://tech.michaelaltfield.net/2020/07/23/sphinx-rtd-github-pages-2/

**Comment by munkm** [comment]
I think sphinx uses the `version` and `release` variables to build separate versions of the docs. Definitely verify this, but I am not sure readthedocs will fix your issue on its own; we need to set the config option to build tagged versions and sphinx (and readthedocs) won't find it unless we set it properly. Once we do, I think the built sphinx docs gh pages will show old versions.

**Comment by yardasol** [comment]
@munkm Okay. Can I commit changes to the `conf.py` files (if needed) on the `v0.x.0` branches?

**Comment by yardasol** [comment]
Okay, so I've looked through the sphinx docs and I don't see this config option for building tagged versions. I agree that we'll need to set the `version` and `release` vars in the `conf.py`, but I do not think  that sphinx + gh-pages have the capability to automatically show older version of the documentation in this way (there is no reference to this behavior in either the sphinx docs or the gh-pages docs).

Luckily, there is a semi-active package that seems to support what we want to do here. It's called [sphinx-multiversion](https://holzhaus.github.io/sphinx-multiversion/master/index.html). I'll see if I can get it to play nice with our docs.

**Comment by yardasol** [comment]
`sphinx-multiversion` does indeed work! It took a bit of tinkering with the `conf.py` file, but I think I'm ready to make a full PR soon
