### ISSUE TITLE
Feature: Docs overhaul

### ISSUE THREAD

**Issue by yardasol** [arfc/saltproc#109]
## Background and motivation
SaltProc has two thesis and several papers in which it is used, however it does not have a narrative, step=by-step user's guide. What currently exists in the online docs is a bit sparse.

## Description of idea
SaltProc should have a user's guide that is narrative, step-by-step, and fully formed.
The docs should also have infomation and references to input and output file structure, publications, and the theory/context of the code.

## Implementation details
I predict that we will need to do several things:
- [x] Reorganize the current structure of the docs to make navigation easier when there are more docpages
- [ ] Make python notebooks that users can use to run examples quickly and easily
- [ ] Make scripts where necessary for pre and post-processing steps
- [ ] Specific docpages (in no particular list order, nest order is relevant):
  - [x] File Format Specification
    - [x] Input Files
    - [x] Output Files
 - [ ] Theory Page
 - [ ] Publications page
 - [x] Dev Guide
   - [ ] Style
     - [ ] Issues/Feature requests
     - [ ] PRs
        - [ ] Add comments in template on how users should describe their changes (it should be a bulleted list using nesting where appropriate)
 - [x] User's Guide
   - [x] Basics
    - [x] Installing SaltProc
    - [ ] ~~Installing depletion code~~
    - [ ] ~~Setting up XS library~~
   - [x] Creating an input file
   - [x] Creating a dot file
   - [x] Creating a process file
     - [ ] Custom and time-dependent extraction efficiencies 
   - [x] Running a simulation
     - [x] Geometry switching when keff will drop below 1
   - [ ] Processing results

We should also rename `doc/src` to `doc/api`.

This feature is too large and requires too much care to be part of the 0.4.0 release.

## Potential snags
We may need to modify `app.py` to enable in-notebook running of the code.

**Comment by munkm** [comment]
This is an excellent feature request!
