### ISSUE TITLE
[Bug]: Unintended cascade of workflow runs 

### ISSUE THREAD

**Issue by yardasol** [arfc/saltproc#125]
## Expected behavior
When we publish a release on github, the following actions should run in the following order:
1. `next-release-minor.yml`
2. `populate-releasenotes.yml`
2. `deploy-docs.yml`

## Describe the bug
The following cascade of workflows ran when we published 0.4.0:
1. `deploy-docs.yml` Triggered via release: @[yardasol](https://github.com/yardasol) published [v0.4.0](https://github.com/arfc/saltproc/releases/tag/v0.4.0). Passed
2. `next-release-minor.yml` triggered via release: @[yardasol](https://github.com/yardasol) published [v0.4.0](https://github.com/arfc/saltproc/releases/tag/v0.4.0). Failed:
```
 HEAD detached from v0.4.0
nothing to commit, working tree clean
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Process completed with exit code 128.
```
3. `test-saltproc.yml` Triggered via push: @[yardasol](https://github.com/yardasol) pushed c6b3d60 [v0.4.0](https://github.com/arfc/saltproc/tree/v0.4.0). Passed
4. `deploy-docs.yml` Triggered via release: @[yardasol](https://github.com/yardasol) edited [v0.4.0](https://github.com/arfc/saltproc/releases/tag/v0.4.0). Failed:
```
 /usr/bin/git push origin gh-pages
  To https://github.com/arfc/saltproc.git
   ! [remote rejected] gh-pages -> gh-pages (cannot lock ref 'refs/heads/gh-pages': is at 51e6cb39791df2755dc5045a0c61fb5192ea4307 but expected 5207c91751db83dfe4fddebf821392c6156258ba)
  error: failed to push some refs to 'https://github.com/arfc/saltproc.git'
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"
```
5. `deploy-docs.yml` Triggered via release: @[yardasol](https://github.com/yardasol) edited [v0.4.0](https://github.com/arfc/saltproc/releases/tag/v0.4.0). PASSED
6. `populate-releasenotes.yml` Triggered via push: @[yardasol](https://github.com/yardasol) pushed c6b3d60 [v0.4.0](https://github.com/arfc/saltproc/tree/v0.4.0). FAILED:
```
Run pandoc -s -o RELEASENOTES.md -f rst -t gfm doc/releasenotes/v0.5.0.rst --columns 1000
pandoc: doc/releasenotes/v0.5.0.rst: openBinaryFile: does not exist (No such file or directory)
Error: Process completed with exit code 1.
```
7. `next-release-minor.yml` Triggered via releaseL @[yardasol](https://github.com/yardasol) edited [v0.4.0](https://github.com/arfc/saltproc/releases/tag/v0.4.0). FAILED:
```
Run gh api repos/arfc/saltproc/milestones \
  gh api repos/arfc/saltproc/milestones \
  -H "Authorize: token ***" \
  -H "Accept: application/vnd.github.v3+json" \
  -X POST \
  -F title=v0.5.0 
  shell: /usr/bin/bash -l {0}
  env:
    RELEASE_VERSION: v0.4.0
    NEW_RELEASE_VERSION: v0.5.0
    GITHUB_TOKEN: ***
gh: Validation Failed (HTTP 422)
{"message":"Validation Failed","errors":[{"resource":"Milestone","code":"already_exists","field":"title"}],"documentation_url":"https://docs.github.com/rest/reference/issues#create-a-milestone"}
Error: Process completed with exit code 1.
```
8. `next-release-minor.yml` Triggered via release: @[yardasol](https://github.com/yardasol) released [v0.4.0](https://github.com/arfc/saltproc/releases/tag/v0.4.0). FAILED:
```
Run gh api repos/arfc/saltproc/milestones \
  gh api repos/arfc/saltproc/milestones \
  -H "Authorize: token ***" \
  -H "Accept: application/vnd.github.v3+json" \
  -X POST \
  -F title=v0.5.0 
  shell: /usr/bin/bash -l {0}
  env:
    RELEASE_VERSION: v0.4.0
    NEW_RELEASE_VERSION: v0.5.0
    GITHUB_TOKEN: ***
gh: Validation Failed (HTTP 422)
{"message":"Validation Failed","errors":[{"resource":"Milestone","code":"already_exists","field":"title"}],"documentation_url":"https://docs.github.com/rest/reference/issues#create-a-milestone"}
Error: Process completed with exit code 1.
```
9. `deploy-docs.yml` Triggered via release: @[yardasol](https://github.com/yardasol) released [v0.4.0](https://github.com/arfc/saltproc/releases/tag/v0.4.0). FAILED:
```
Push the commit or tag
  /usr/bin/git push origin gh-pages
  To https://github.com/arfc/saltproc.git
   ! [rejected]        gh-pages -> gh-pages (fetch first)
  error: failed to push some refs to 'https://github.com/arfc/saltproc.git'
  hint: Updates were rejected because the remote contains work that you do
  hint: not have locally. This is usually caused by another repository pushing
  hint: to the same ref. You may want to first integrate the remote changes
  hint: (e.g., 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"
```

## To Reproduce
1. Don't do this

## System Specifications:
 
 - Software version: 0.4.0
 - Subsystem: Github Actions: `ubuntu-latest` runner

## How can this issue be closed?
Some points of note:
1. The first run of `deploy-docs.yml` was triggered by publishing 0.4.0. **The `published` trigger should be removed from this workflow**, since `next-release-minor.yml` makes changes that will trigger `deploy-docs.yml` anyways.
2. The first run of `next-release-minor.yml` failed due to **improper git commands** (specifically, not pushing to HEAD)
3. The 2nd and 3rd run of `deploy-docs.yml` occurred at the same time, so there was a race-condition that caused one of them to fail when pushing to `gh-pages`. They were triggered by editing the v0.4.0 release body (this is a `published` webhook event, so it will trigger the workflow). Again, another reason to remove that trigger from `deploy-docs.yml`
4.  The first run of `populate-releasenotes.yml` failed because the `v0.5.0.rst` file that was supposed to be created by `next-release-minor.yml` was never created due to that run failing. This workflow was triggered by the creation of the v0.4.0 tag. **We should modify the triggers for this action so that it only runs from activity on the master branch**
5. The 2nd and 3rd run of `next-release-minor.yml` both failed due to the v0.5.0 milestone already being created in the first place. These workflows should not have been triggered in the first place. One of the webhooks was `released` and another was `edited`. **We should specify that this workflow only runs when a release is actually `released`**

**Comment by munkm** [comment]
Thanks for this write up; you've been very clear and I think this helps us find places to improve. 

I think you can force actions to trigger in a sequential order. Maybe it would be helpful to require that the previous action passed before running the next one? What do you think?
