### ISSUE TITLE
[Bug]: Unfinished `next-release-minor` workflow tasks

### ISSUE THREAD

**Issue by yardasol** [arfc/saltproc#128]
## Expected behavior

1. There should be a `v0.5.0.rst` release notes file in `doc/releasenotes` on the `master` branch
2. The github-pages version of the `v0.4.0` release notes should not specify that the notes are in production.
3. `saltproc/version.py::_version_minor` should have a value of `5` in the `master` branch
4. `saltproc/version.py::_version_extra` should have a value of `'0'` in the `v0.4.0` tag

## Describe the bug

The opposite of items 1 and 2 are true, the current value of `_version_minor` in the `master` branch is `4`, and the value of `_version_extra` in the `v0.4.0` tag is `'dev'`. These discrepancies are in combination due to the failure of the workflows detailed in #125, as well as a lack of proper procedures to update `version.py` as described in #129

## To Reproduce
1. Look at the referenced files and locations.

## System Specifications:
 
 - Software version: SaltProc v0.4.0-dev

## How can this issue be closed?
This issue can be closed when a PR exists that corrects each of the above items.

Items 1, 2, and 3 are relatively straightforward. Item 4 is trickier and needs careful consideration. We may need to implement #116 to fully address item 4.

**Comment by yardasol** [comment]
Also, @munkm, since the tagged release has the incorrect version, how to we fix it? Delete and re-release?

**Comment by munkm** [comment]
> Also, @munkm, since the tagged release has the incorrect version, how to we fix it? Delete and re-release?

Yep I think that's the best course of action here.
