### ISSUE TITLE
[Meta] Work order for remaining PRs/Issues for OpenMC support

### ISSUE THREAD

**Issue by yardasol** [arfc/saltproc#163]
1. #160 
2. #161 
3. Depcode issues
    - #162
    - #176 
    - #178
    - #171
4. #173 
5. #133
6. #109 
7. Cleanup `Simulation` class and related code, #120, #93, #180
8. #191

**Comment by khurrumsaleem** [comment]
Hi,

@yardasol I just wanted to ask that can we use OpenMC as depletion code now or still have to wait for release of 0.5.0.?

Secondly will it be possible for you to add an example in examples folder for using OpenMC ad depletion code.

Thanks

**Comment by yardasol** [comment]
@khurrumsaleem OpenMC support will be available once 0.5.0 is released. An example case will be included in the release

**Comment by khurrumsaleem** [comment]
Thanks @yardasol

**Comment by yardasol** [comment]
@khurrumsaleem There will most likely be a prerelease once item 5 is finished. This is to have a reference-able version for my Master's thesis. The rest of the features will be competed after the thesis is submitted.

**Comment by yardasol** [comment]
@khurrumsaleem There is a pre-release of v0.5.0 that should be have fully functional OpenMC support. Please check it out and let me know what you think!

**Comment by yardasol** [comment]
All of these are done!
