### ISSUE TITLE
store meaningful values, not input file parameters

### ISSUE THREAD

**Issue by jbae11** [arfc/saltproc#25]
Currently saltproc stores either atomic density and mass fraction.
These values are not valuable by themselves and require total salt volume or mass.
Saltproc should store meaningful data such as mass of isotope

**Comment by jbae11** [comment]
since output of _dep.m file in mass density, we create another variable for Saltproc called `blanket_vol` and `driver_vol`. Multiplying the mass densities by volume gives us mass. Store all db values with mass.

**Comment by andrewryh** [comment]
Teddy made conversation to mass and everything stored in HDF5 in [kg]
