### ISSUE TITLE
Set up continuous integration for salt proc

### ISSUE THREAD

**Issue by katyhuff** [arfc/saltproc#26]
Consider circleci or travis. (it doesn't seem to be git-hooked into PRs)

**Comment by andrewryh** [comment]
Will do it closer to SaltProc v1.0 Release

**Comment by katyhuff** [comment]
Please set up ASAP.

**Comment by andrewryh** [comment]
@katyhuff Looks like I do not have permissions on `arfc/saltproc` to set up CI.
This is weird because I made this repo, and I have owner permissions for any repo I created.
But not for saltproc.

Could you please use your super-access to check it out?

**Comment by andrewryh** [comment]
Done #37
