### ISSUE TITLE
Add docs to continuous integration

### ISSUE THREAD

**Issue by katyhuff** [arfc/saltproc#35]
In parallel, or just after completion of #26, push built documentation to a web location (arfc.github.com/saltproc will be where github puts anything in the gh-pages branch of saltproc.)

**Comment by andrewryh** [comment]
@katyhuff It appears I do not have full control under arfc/saltproc, so, I cannot enable Github Pages there.
But I made it in my local fork and its working: https://andrewryh.github.io/saltproc/

You might want to move it to https://arfc.github.io/saltproc/ during our code review session next Tuesday.

**Comment by andrewryh** [comment]
This is done.
See PR #37

**Comment by andrewryh** [comment]
Fixed in #37
