### ISSUE TITLE
The tap_main.json example file fails to run due to filepath issues.

### ISSUE THREAD

**Issue by smpark7** [arfc/saltproc#38]
When running the tap_main.json example, the Serpent run fails due to the relative filepath in line 4 of tap.serpent.

Line 4: ```include "mat/non_burnable_mats.ini```

**Comment by andrewryh** [comment]
This error appears only with Serpent version <2.1.31.
For 2.1.31 works fine.
Will change documentation to require Serpent 2.1.31 or newer.

**Comment by andrewryh** [comment]
@smpark7 I think, it should work after updating Serpent to 2.1.31.
Please check it out and approve #37

**Comment by andrewryh** [comment]
Works well with  Serpent to 2.1.31.
