### ISSUE TITLE
Creat JSON schema for input

### ISSUE THREAD

**Issue by katyhuff** [arfc/saltproc#42]
Structure the input file based on a validation-ready json input file schema. This schema should be helped by description docstrings where necessary. However, a description of each variable that each input parameter becomes at runtime should be present in the class where that variable appears. (declare private or public variable where appropriate).

**Comment by katyhuff** [comment]
https://json-schema.org/understanding-json-schema

**Comment by andrewryh** [comment]
```
{"depcode":{
  "codename": "sss2",
  "serpent": {"file_path": "file/path",
  "nuetrons": 20}
  "opeMC": {this is optional} 
},
},
{"materialflow":{
  
  }}
}
```

**Comment by andrewryh** [comment]
A Good material to learn about JSON schema: https://json-schema.org/understanding-json-schema/

**Comment by yardasol** [comment]
@andrewryh did you ever finish implementing this?

**Comment by yardasol** [comment]
Working on an implementation in #98. It's 99% done, but I need to figure out how to add the `.json` file to the package when running `pip install .`
