### ISSUE TITLE
Separation of concerns

### ISSUE THREAD

**Issue by katyhuff** [arfc/saltproc#44]
- [x] The simulation class should only know enough to do a small number of things specific to the simulation mangement.
- [x] #59
- [x] Other classes should implement the stuff that is specific to the depletion code chosen (these should be  instances (which inherit from depcode) like a `serpent2` class, an `openmc` class, etc.)
- [ ] the geometry changing should be in its own file probably.
- [x] the template reading and writing should be closer to the depcode class (maybe in in the serpent class).
- [x] maybe the app class and the simulation class should be merged, then separated back out so that there is a separation of concern.

**Comment by yardasol** [comment]
Upon further inspection of the code, it seems most of these have been completed tasks. @katyhuff @andrewryh can you confirm? May need to look at the code with @munkm to verify.
