### ISSUE TITLE
Build and Run RAVEN on Blue Waters

### ISSUE THREAD

**Issue by katyhuff** [arfc/saltproc#5]
This issue can be closed when :

- [x] RAVEN has been cloned,
- [x] built
- [ ] and run

on blue waters.

**Comment by jbae11** [comment]
RAVEN is built on BW with all tests successful.

**Comment by katyhuff** [comment]
Where is it? In the group directory or in your home directory?

**Comment by jbae11** [comment]
both! in bagh and bae

**Comment by andrewryh** [comment]
`/projects/sciteam/bahg/projects/raven`

**Comment by katyhuff** [comment]
perfect! Thanks both!
