### ISSUE TITLE
Feature: CI overhaul

### ISSUE THREAD

**Issue by yardasol** [arfc/saltproc#81]
**Background and motivation**
The current CI workflow is fine for now, but in the future if we want to do anything like automated deployments of online documentation to the saltproc website or run OpenMC integration tests, we will need to heavily edit how our workflow structure and implementation

**Description of idea**
I've identified the following areas that we could improve and add to our CI/CD workflow:
 - [ ] Matrix testing of multiple python versions, operating systems
 - [x] Conda environment setup and caching
 - [x] Automated building and deployment of docs
 - [ ] flake8 linting
 - [ ] OpenMC integration testing 

**Implementation details**
I have identified the following resources that would be useful in completing the itemized goals:
- Conda environment setup and caching:
  - [setup-miniconda action](https://github.com/conda-incubator/setup-miniconda)
  - [GitHub docs on caching workflow dependencies](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key)
  - [Caching conda environments](https://github.com/conda-incubator/setup-miniconda#caching-environments)
- Automated building and deployment of docs
  - [sphinx-action-test action](https://github.com/ammaraskar/sphinx-action-test) (includes examples on how to deploy to gh-pages)
  - [GitHub docs on storing workflow data as artifacts](https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts)
  - [Moltres workflow for doing this](https://github.com/arfc/moltres/blob/devel/.github/workflows/auto-update-gh-pages.yml)
- OpenMC integration testing
  - none yet
- Miscellaneous
  - [Service containers](https://docs.github.com/en/actions/using-containerized-services/about-service-containers)

**Potential snags**
This requires some pretty decent working knowledge of using GitHub actions, which could be a barrier to doing this quickly as its still a relativley new tool.

**Comment by yardasol** [comment]
Doing this with mamba/conda is kinda messy. I want to try to do this with pip.

Some helpfil links
- [stackoverflow post](https://stackoverflow.com/questions/59127258/how-can-i-use-pip-cache-in-github-actions)
- [cache-python](https://github.com/actions/setup-python)
-

**Comment by munkm** [comment]
Were you working on a particular item in this list that got messy with mamba and/or conda? What happened?

**Comment by yardasol** [comment]
It has to do with the way I want to implement workflows. I want different workflows for
- Installing the dependencies and building saltproc (runs on push to a PR; only need to do this once every week, unless there's an update in a package we want)
- Testing saltproc (runs on push to a PR)
- building and deploying the docs (runs on PR merge into master)

I only want to have to install dependencies once, so that I can use them to build saltproc quickly for doing the other two workflows. This means we should cache the dependencies. It seems there are few different ways to do caching with conda, and they all require more configuration of the workflow file. For simplicity (and my sanity) I want to use pip to abstract out the details of caching with conda, and if I want to come back to it later once things are working the way I want them to. 

It's possible I'm thinking about this all wrong though.

**Comment by yardasol** [comment]
I think this can be marked as completed. I completed most of the features described in this issue in PR #95. I do not think it is reasonable to try to run OpenMC integration tests here. I do think that flake8 linting and matrix testing with multiple versions of python would be useful, so I'll make separate issues for each of those.
